// APP ACTIONS
export const CHANGE_INPUT = 'CHANGE_INPUT';
export const OPEN_MODAL = 'OPEN_MODAL';
export const APP_CHANGE_LANGUAGE = 'APP_CHANGE_LANGUAGE';

// SEARCH
export const SEARCH = 'SEARCH';
export const SET_SEARCH_VALUES = 'SET_SEARCH_VALUES';
export const CLEAR_SEARCH_VALUES = 'CLEAR_SEARCH_VALUES';

// PARTNERS
export const GET_PARTNER_R = 'GET_PARTNER_R';
export const GET_PARTNER_S = 'GET_PARTNER_S';
export const GET_PARTNER_F = 'GET_PARTNER_F';

export const POST_PARTNER_R = 'POST_PARTNER_R';
export const POST_PARTNER_S = 'POST_PARTNER_S';
export const POST_PARTNER_F = 'POST_PARTNER_F';

export const DELETE_PARTNER_R = 'DELETE_PARTNER_R';
export const DELETE_PARTNER_S = 'DELETE_PARTNER_S';
export const DELETE_PARTNER_F = 'DELETE_PARTNER_F';

export const UPDATE_PARTNER_R = 'UPDATE_PARTNER_R';
export const UPDATE_PARTNER_S = 'UPDATE_PARTNER_S';
export const UPDATE_PARTNER_F = 'UPDATE_PARTNER_F';

// CITIES
export const GET_CITY_R = 'GET_CITY_R';
export const GET_CITY_S = 'GET_CITY_S';
export const GET_CITY_F = 'GET_CITY_F';

export const POST_CITY_R = 'POST_CITY_R';
export const POST_CITY_S = 'POST_CITY_S';
export const POST_CITY_F = 'POST_CITY_F';

// BUSINESS FORMS
export const GET_BUSINESS_FORM_R = 'GET_BUSINESS_FORM_R';
export const GET_BUSINESS_FORM_S = 'GET_BUSINESS_FORM_S';
export const GET_BUSINESS_FORM_F = 'GET_BUSINESS_FORM_F';

export const POST_BUSINESS_FORM_R = 'POST_BUSINESS_FORM_R';
export const POST_BUSINESS_FORM_S = 'POST_BUSINESS_FORM_S';
export const POST_BUSINESS_FORM_F = 'POST_BUSINESS_FORM_F';
